/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spacelevelup.projectimageevents;

/**
 *
 * @author Lee_Dan
 */
public class ImagesTesteEventos extends javax.swing.JFrame {

    /**
     * Creates new form ImagesTesteEventos
     */
    public ImagesTesteEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnClick = new javax.swing.JButton();
        jLabelResult = new javax.swing.JLabel();
        jBtnMouse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jbtnClick.setText("Click");
        jbtnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClickActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClick);
        jbtnClick.setBounds(10, 30, 70, 23);

        jLabelResult.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelResult.setText("Resultado");
        getContentPane().add(jLabelResult);
        jLabelResult.setBounds(10, 270, 260, 14);

        jBtnMouse.setText("Ao passar o mouse na área do botão");
        jBtnMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnMouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnMouseMouseExited(evt);
            }
        });
        getContentPane().add(jBtnMouse);
        jBtnMouse.setBounds(93, 30, 220, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClickActionPerformed
        // TODO add your handling code here:

        
        if("vamos lá".equals(jLabelResult.getText())){
        jLabelResult.setText("Click no botão");
        }else{
        jLabelResult.setText("vamos lá");
        }
    }//GEN-LAST:event_jbtnClickActionPerformed

    private void jBtnMouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMouseMouseEntered
        // TODO add your handling code here:
        jLabelResult.setText("Mouse entrou na área do botão");
        
    }//GEN-LAST:event_jBtnMouseMouseEntered

    private void jBtnMouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMouseMouseExited
        // TODO add your handling code here:
        
        jLabelResult.setText("Saiu da área do botão");

        
    }//GEN-LAST:event_jBtnMouseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImagesTesteEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImagesTesteEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImagesTesteEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImagesTesteEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImagesTesteEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnMouse;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JButton jbtnClick;
    // End of variables declaration//GEN-END:variables
}
