/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spacelevelup.projectimageevents;
import javax.swing.ImageIcon;

/**
 *
 * @author Lee_Dan
 */
public class ImagesTesteEventos extends javax.swing.JFrame {

    /**
     * Creates new form ImagesTesteEventos
     */
    public ImagesTesteEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnClick = new javax.swing.JButton();
        jLabelResult = new javax.swing.JLabel();
        jBtnMouse = new javax.swing.JButton();
        jBtnFoco = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jButtonImage1 = new javax.swing.JButton();
        jButtonImage2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jbtnClick.setText("Click");
        jbtnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClickActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClick);
        jbtnClick.setBounds(10, 10, 70, 23);

        jLabelResult.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelResult.setText("Resultado");
        getContentPane().add(jLabelResult);
        jLabelResult.setBounds(70, 420, 160, 14);

        jBtnMouse.setText("Ao passar o mouse na área do botão");
        jBtnMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnMouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnMouseMouseExited(evt);
            }
        });
        getContentPane().add(jBtnMouse);
        jBtnMouse.setBounds(100, 10, 220, 23);

        jBtnFoco.setText("Foco");
        jBtnFoco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBtnFocoFocusGained(evt);
            }
        });
        getContentPane().add(jBtnFoco);
        jBtnFoco.setBounds(340, 10, 55, 23);

        jLabelImage.setText("Imagem");
        getContentPane().add(jLabelImage);
        jLabelImage.setBounds(20, 44, 510, 340);

        jButtonImage1.setText("Emo +");
        jButtonImage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImage1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImage1);
        jButtonImage1.setBounds(290, 420, 80, 23);

        jButtonImage2.setText("Emo -");
        jButtonImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImage2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImage2);
        jButtonImage2.setBounds(380, 420, 73, 23);

        setBounds(0, 0, 567, 487);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClickActionPerformed
        // TODO add your handling code here:

        
        if("vamos lá".equals(jLabelResult.getText())){
        jLabelResult.setText("Click no botão");
        }else{
        jLabelResult.setText("vamos lá");
        }
    }//GEN-LAST:event_jbtnClickActionPerformed

    private void jBtnMouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMouseMouseEntered
        // TODO add your handling code here:
        jLabelResult.setText("Mouse entrou na área do botão");
        
    }//GEN-LAST:event_jBtnMouseMouseEntered

    private void jBtnMouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMouseMouseExited
        // TODO add your handling code here:
        
        jLabelResult.setText("Saiu da área do botão");

        
    }//GEN-LAST:event_jBtnMouseMouseExited

    private void jBtnFocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBtnFocoFocusGained
        // TODO add your handling code here:
        jLabelResult.setText("O botão recebeu foco");
        
    }//GEN-LAST:event_jBtnFocoFocusGained

    private void jButtonImage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImage1ActionPerformed
        // TODO add your handling code here
        ImageIcon icon = new ImageIcon("D:/Sistema/Videos/lee/Eu/emo.jpg");
        jLabelImage.setIcon(icon);
    }//GEN-LAST:event_jButtonImage1ActionPerformed

    private void jButtonImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImage2ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("D:/Sistema/Videos/lee/Eu/linda.jpg");
        jLabelImage.setIcon(icon);
    }//GEN-LAST:event_jButtonImage2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImagesTesteEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImagesTesteEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImagesTesteEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImagesTesteEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImagesTesteEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFoco;
    private javax.swing.JButton jBtnMouse;
    private javax.swing.JButton jButtonImage1;
    private javax.swing.JButton jButtonImage2;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JButton jbtnClick;
    // End of variables declaration//GEN-END:variables
}
